### ISSUE TITLE
From FRC Team 3196 - Need clean build

### ISSUE THREAD

**Issue by adurstewitz** [Shenzhen-Robotics-Alliance/Maple-Swerve-Skeleton#42]
Hello! First off, thank you all so much for the amazing work on this template. I'm one of the mentors from FRC 3196 and we're working to merge our existing 2024 robot code in with this emulator so we have a starting point for 2025. My question is, would it be possible for you all to publish a clean build for us to pull from? Not sure if that possible based on your dev cycle, but if you were able to that would be awesome.

To clarify, after updating PathPlanner we're getting the following error -

* What went wrong:
An exception occurred applying plugin request [id: 'edu.wpi.first.GradleRIO', version: '2024.3.2']
> Failed to apply plugin class 'edu.wpi.first.gradlerio.wpi.WPIPlugin'.
   > Could not create an instance of type edu.wpi.first.gradlerio.wpi.WPIExtension.
      > Vendor Dependency PathplannerLib has invalid year 2025. Expected to be 2024. Reach out to the vendor to get a new version of the dependency. Attempting to modify an existing dependency will break at runtime, and will result in loss of support from the WPILib team.

Thanks! Andrew

**Comment by catr1xLiu** [comment]
Hey!  So excited to hear that your team is doing that!  I'm sorry to tell you that maple-swerve-skeleton is discontinued as a public project.  If you want to implement the emulator in your robot code, I would recommend maple-sim, which is a library that can help you implement the simulations in your project, without having to merge the entire code base.
https://www.chiefdelphi.com/t/maple-sim-alpha-bringing-robot-simulations-to-the-next-level-with-physics-engines/473238

**Comment by catr1xLiu** [comment]
Sorry for the trouble it's causing now.  I'll create a dev branch later this week where test unreleased features of maple-sim will be tested.  This way the main branch gets a clean build.

**Comment by catr1xLiu** [comment]
After upgrading to maple-sim v0.2.0, the main branch [has a clean build ](https://github.com/Shenzhen-Robotics-Alliance/Maple-Swerve-Skeleton/actions/runs/11964683484) now.

Future development progress will be in the `dev` branch, and `main` will always have a clean build.
