### ISSUE TITLE
MapleSim not found

### ISSUE THREAD

**Issue by Kouyang07** [Shenzhen-Robotics-Alliance/Maple-Swerve-Skeleton#43]
I cloned this repo and tried to run it. I got the error 
```
Build file '/Users/kouyang/IdeaProjects/MapleSim/build.gradle' line: 124

Could not determine the dependencies of task ':jar'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not find org.ironmaple:maplesim-java:0.1.7prev.
     Searched in the following locations:
       - https://maven.pkg.github.com/Mechanical-Advantage/AdvantageKit/org/ironmaple/maplesim-java/0.1.7prev/maplesim-java-0.1.7prev.pom
       - file:/Users/kouyang/.m2/repository/org/ironmaple/maplesim-java/0.1.7prev/maplesim-java-0.1.7prev.pom
       - file:/Users/kouyang/wpilib/2025/maven/org/ironmaple/maplesim-java/0.1.7prev/maplesim-java-0.1.7prev.pom
       - https://frcmaven.wpi.edu/artifactory/vendor-mvn-release/org/ironmaple/maplesim-java/0.1.7prev/maplesim-java-0.1.7prev.pom
       - https://shenzhen-robotics-alliance.github.io/maple-sim/vendordep/repos/releases/org/ironmaple/maplesim-java/0.1.7prev/maplesim-java-0.1.7prev.pom
       - https://repo.maven.apache.org/maven2/org/ironmaple/maplesim-java/0.1.7prev/maplesim-java-0.1.7prev.pom
     Required by:
         project :

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 1s
```

https://shenzhen-robotics-alliance.github.io/maple-sim/vendordep/maple-sim.json
This link works but I am getting the error ```package org.ironmaple.simulation.motorsims does not exist``` so I am assuming the library has a decently large change between preview and 0.1.6

**Comment by Kouyang07** [comment]
https://shenzhen-robotics-alliance.github.io/maple-sim/vendordep/maple-sim.json

This one works

**Comment by catr1xLiu** [comment]
Currently, maple-swerve-skeleton depends on this unreleased version of maple-sim.

Since a few teams are using it, I will soon create a dev branch to test unreleased features.

Sorry for the trouble that it cause now, please download https://github.com/Shenzhen-Robotics-Alliance/maple-sim/tree/dev and publish to maven local.

**Comment by catr1xLiu** [comment]
We have released [maple-sim beta1](https://github.com/Shenzhen-Robotics-Alliance/maple-sim/releases/tag/beta1)!

Now, the `main` branch will use the stable version of maple-sim, so it should be stable too.

Developments will continue in the `dev` branch and will be merged into `main` whenever maple-sim release a new version
